const UserAction = {
  PENDING_SIGN_IN: "SIGN_IN",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILED: "SIGN_IN_FAILED",

  PENDING_SIGN_UP: "SIGN_UP",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILED: "SIGN_UP_FAILED",

  PENDING_SIGN_OUT: "SIGN_OUT",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILED: "SIGN_OUT_FAILED",

  PENDING_GET_USER_INFO: "GET_USER_INFO",
  GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
  GET_USER_INFO_FAILED: "GET_USER_INFO_FAILED",

  CLEAN_USER_INFO: "CLEAR_USER_INFO",
};

const CategoriesAction = {
  PENDING_VIEW_CATEGORIES: "VIEW_CATEGORIES",
  VIEW_CATEGORIES_SUCCESS: "VIEW_CATEGORIES_SUCCESS",
  VIEW_CATEGORIES_FAILED: "VIEW_CATEGORIES_FAILED",

  PENDING_VIEW_CATEGORY: "VIEW_CATEGORY",
  VIEW_CATEGORY_SUCCESS: "VIEW_CATEGORY_SUCCESS",
  VIEW_CATEGORY_FAILED: "VIEW_CATEGORY_FAILED",

  PENDING_CREATE_CATEGORY: "CREATE_CATEGORY",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_FAILED: "CREATE_CATEGORY_FAILED",

  PENDING_UPDATE_CATEGORY: "UPDATE_CATEGORY",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAILED: "UPDATE_CATEGORY_FAILED",

  CLEAR_CATEGORY_INFO: "CLEAR_CATEGORY_INFO",
};

const ItemsAction = {
  PENDING_VIEW_ITEMS: "VIEW_ITEMS",
  VIEW_ITEMS_SUCCESS: "VIEW_ITEMS_SUCCESS",
  VIEW_ITEMS_FAILED: "VIEW_ITEMS_FAILED",

  PENDING_VIEW_ITEM: "VIEW_ITEM",
  VIEW_ITEM_SUCCESS: "VIEW_ITEM_SUCCESS",
  VIEW_ITEM_FAILED: "VIEW_ITEM_FAILED",

  PENDING_CREATE_ITEM: "CREATE_ITEM",
  CREATE_ITEM_SUCCESS: "CREATE_ITEM_SUCCESS",
  CREATE_ITEM_FAILED: "CREATE_ITEM_FAILED",

  PENDING_UPDATE_ITEM: "UPDATE_ITEM",
  UPDATE_ITEM_SUCCESS: "UPDATE_ITEM_SUCCESS",
  UPDATE_ITEM_FAILED: "UPDATE_ITEM_FAILED",

  PENDING_DELETE_ITEM: "DELETE_ITEM",
  DELETE_ITEM_SUCCESS: "DELETE_ITEM_SUCCESS",
  DELETE_ITEM_FAILED: "DELETE_ITEM_FAILED",

  CLEAR_ITEM_INFO: "CLEAR_ITEM_INFO",
};

const ModalAction = {
  SHOW_MODAL: "SHOW_MODAL",
  CLEAR_MODAL: "CLEAR_MODAL",
};

const UserInputAction = {
  ON_CHANGE: "ON_CHANGE",
  ON_VALIDATE: "ON_VALIDATE",
  TYPE_ADD: "ADD",
  TYPE_EDIT: "EDIT",
};

const GeneralAction = {
  NETWORK_ERROR: "NETWORK_ERROR",
  NETWORK_OK: "NETWORK_OK",
};

export {
  UserAction,
  CategoriesAction,
  ItemsAction,
  ModalAction,
  UserInputAction,
  GeneralAction,
};
