class KUserActions {
  static PENDING_SIGN_IN = "SIGN_IN";
  static SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
  static SIGN_IN_FAILED = "SIGN_IN_FAILED";

  static PENDING_SIGN_UP = "SIGN_UP";
  static SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
  static SIGN_UP_FAILED = "SIGN_UP_FAILED";

  static PENDING_SIGN_OUT = "SIGN_OUT";
  static SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
  static SIGN_OUT_FAILED = "SIGN_OUT_FAILED";
}

class KCategoriesAction {
  static PENDING_VIEW_CATEGORIES = "VIEW_CATEGORIES";
  static VIEW_CATEGORIES_SUCCESS = "VIEW_CATEGORIES_SUCCESS";
  static VIEW_CATEGORIES_FAILED = "VIEW_CATEGORIES_FAILED";

  static PENDING_CREATE_CATEGORY = "CREATE_CATEGORY";
  static CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
  static CREATE_CATEGORY_FAILED = "CREATE_CATEGORY_FAILED";
}

export { KUserActions, KCategoriesAction };
